apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-worker
  labels:
    app: temporal-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-worker
  template:
    metadata:
      labels:
        app: temporal-worker
    spec:
      containers:
        - name: temporal-worker
          image: jasongill00/temporal-worker:latest 
          env:
            - name: VERSION
              value: "{{ YOUR_TAG }}"
            - name: NODE_ENV
              value: production
            - name: TEMPORAL_CLOUD_ADDRESS
              value: us-east-1.aws.api.temporal.io:7233
            - name: TEMPORAL_CLOUD_NAMESPACE
              value: test-playground
            - name: TEMPORAL_CLOUD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: temporal-api-key
                  key: TEMPORAL_CLOUD_API_KEY
          volumeMounts:
            - name: temporal-creds
              mountPath: /creds
              readOnly: true
      volumes:
        - name: temporal-creds
          secret:
            secretName: temporal-credentials
