name: Deploy to EKS

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: jasongill00/test-project
  IMAGE_TAG: ${{ github.sha }}
  TEMPORAL_WORKER_IMAGE_NAME: jasongill00/temporal-worker
  TEMPORAL_WORKER_IMAGE_TAG: ${{ github.sha }}
  TEMPORAL_CLIENT_KEY: ${{ secrets.TEMPORAL_CLIENT_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push api-server Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    - name: Build and push temporal Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./worker.dockerfile   # ← THIS IS IMPORTANT
        push: true
        tags: ${{ env.TEMPORAL_WORKER_IMAGE_NAME }}:${{ env.TEMPORAL_WORKER_IMAGE_TAG }}
          

    # - name: Build and push temoral Docker image
    #   uses: docker/build-push-action@v5
    #   with:
    #     context: .
    #     push: true
    #     tags: ${{ env.TEMPORAL_WORKER_IMAGE_NAME }}:${{ env.TEMPORAL_WORKER_IMAGE_TAG }}

    - name: Update image tag in deployment.yaml
      run: |
        sed -i "s|image: $IMAGE_NAME.*|image: $IMAGE_NAME:$IMAGE_TAG|" ./kubernetes/deployment.yaml
        sed -i "s|image: $TEMPORAL_WORKER_IMAGE_NAME.*|image: $TEMPORAL_WORKER_IMAGE_NAME:$TEMPORAL_WORKER_IMAGE_TAG|" ./kubernetes/temporal-deployment.yaml

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Update kubeconfig for EKS
      run: |
        aws eks update-kubeconfig --region us-east-1 --name my-cluster 

    - name: Create Kubernetes secret for Temporal API key
      run: |
        kubectl delete secret temporal-api-key --ignore-not-found
        kubectl create secret generic temporal-api-key \
          --from-literal=TEMPORAL_CLOUD_API_KEY=${{ secrets.TEMPORAL_CLIENT_KEY }}

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f ./kubernetes/deployment.yaml
        kubectl apply -f ./kubernetes/service.yaml
        kubectl apply -f ./kubernetes/temporal-deployment.yaml

